// const promiseOne = new Promise((resolve, reject)=>{
//     // DB calls, Cryptography, NetworkCall
//     setTimeout(()=>{
//         console.log('Async task is done');
//         resolve()
//     }, 1000)
// })

// promiseOne.then(()=>{
//     console.log("promise consumed");
    
// })

// new Promise((resolve, reject)=>{
//     setTimeout(()=>{
//         console.log("Async task 2");
//         resolve
//     }, 1000)
// }).then(()=>{
//     console.log("hi");
// })

// const promiseThree = new Promise((resolve, reject)=>{
//     setTimeout(()=>{
//         resolve({username: "chai", email:"chai@email.com"})
//     }, 1000)
// }).then((user)=>{
//     console.log(user);
    
// })

// const promiseFour = new Promise((resolve, reject)=>{
//     setTimeout(()=>{
//         let error = true
//         if (!error) {
//             resolve({username:"jit", password:"12345"})
//         }else{
//             reject ('ERROR: 404')
//         }
//     }, 1000)
// })
// const username = promiseFour.then((user)=>{
//     console.log(user);
//     return user.username  
// }).then((username)=>{
//     console.log(username);
// }).catch((error)=>{
//     console.log(error);   
// }).finally(()=>(console.log("the promise is resolve or rejected")))


// const promiseFive = new Promise((resolve, reject)=>{
//     setTimeout(()=>{
//         let error = true
//         if (!error) {
//             resolve({username:"jit", password:"12345"})
//         }else{
//             reject ('ERROR: 404')
//         }
//     }, 1000)
// });

// async function consumePromiseFive(){
//     try {
//         const response = await promiseFive
//         console.log(response);
//     } catch (error) {
//         console.log(error);
//     }
// }
// consumePromiseFive()

